# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from basket_api.grpc_gen import basket_pb2 as basket__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in basket_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BasketStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBasketById = channel.unary_unary(
                '/BasketApi.Basket/GetBasketById',
                request_serializer=basket__pb2.BasketRequest.SerializeToString,
                response_deserializer=basket__pb2.CustomerBasketResponse.FromString,
                _registered_method=True)
        self.UpdateBasket = channel.unary_unary(
                '/BasketApi.Basket/UpdateBasket',
                request_serializer=basket__pb2.CustomerBasketRequest.SerializeToString,
                response_deserializer=basket__pb2.CustomerBasketResponse.FromString,
                _registered_method=True)


class BasketServicer:
    """Missing associated documentation comment in .proto file."""

    def GetBasketById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBasket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BasketServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBasketById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBasketById,
                    request_deserializer=basket__pb2.BasketRequest.FromString,
                    response_serializer=basket__pb2.CustomerBasketResponse.SerializeToString,
            ),
            'UpdateBasket': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBasket,
                    request_deserializer=basket__pb2.CustomerBasketRequest.FromString,
                    response_serializer=basket__pb2.CustomerBasketResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BasketApi.Basket', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('BasketApi.Basket', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Basket:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBasketById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasketApi.Basket/GetBasketById',
            basket__pb2.BasketRequest.SerializeToString,
            basket__pb2.CustomerBasketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBasket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BasketApi.Basket/UpdateBasket',
            basket__pb2.CustomerBasketRequest.SerializeToString,
            basket__pb2.CustomerBasketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
