# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basket.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'basket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61sket.proto\x12\tBasketApi\"\x1b\n\rBasketRequest\x12\n\n\x02id\x18\x01 \x01(\t\"V\n\x15\x43ustomerBasketRequest\x12\x0f\n\x07\x62uyerid\x18\x01 \x01(\t\x12,\n\x05items\x18\x02 \x03(\x0b\x32\x1d.BasketApi.BasketItemResponse\"W\n\x16\x43ustomerBasketResponse\x12\x0f\n\x07\x62uyerid\x18\x01 \x01(\t\x12,\n\x05items\x18\x02 \x03(\x0b\x32\x1d.BasketApi.BasketItemResponse\"\x97\x01\n\x12\x42\x61sketItemResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tproductid\x18\x02 \x01(\x05\x12\x13\n\x0bproductname\x18\x03 \x01(\t\x12\x11\n\tunitprice\x18\x04 \x01(\x01\x12\x14\n\x0coldunitprice\x18\x05 \x01(\x01\x12\x10\n\x08quantity\x18\x06 \x01(\x05\x12\x12\n\npictureurl\x18\x07 \x01(\t2\xaf\x01\n\x06\x42\x61sket\x12N\n\rGetBasketById\x12\x18.BasketApi.BasketRequest\x1a!.BasketApi.CustomerBasketResponse\"\x00\x12U\n\x0cUpdateBasket\x12 .BasketApi.CustomerBasketRequest\x1a!.BasketApi.CustomerBasketResponse\"\x00\x42\r\xaa\x02\nGrpcBasketb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\nGrpcBasket'
  _globals['_BASKETREQUEST']._serialized_start=27
  _globals['_BASKETREQUEST']._serialized_end=54
  _globals['_CUSTOMERBASKETREQUEST']._serialized_start=56
  _globals['_CUSTOMERBASKETREQUEST']._serialized_end=142
  _globals['_CUSTOMERBASKETRESPONSE']._serialized_start=144
  _globals['_CUSTOMERBASKETRESPONSE']._serialized_end=231
  _globals['_BASKETITEMRESPONSE']._serialized_start=234
  _globals['_BASKETITEMRESPONSE']._serialized_end=385
  _globals['_BASKET']._serialized_start=388
  _globals['_BASKET']._serialized_end=563
# @@protoc_insertion_point(module_scope)
