# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ordering.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'ordering.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eordering.proto\x12\x0bOrderingApi\"R\n\x17\x43reateOrderDraftCommand\x12\x0f\n\x07\x62uyerId\x18\x01 \x01(\t\x12&\n\x05items\x18\x02 \x03(\x0b\x32\x17.OrderingApi.BasketItem\"\x8f\x01\n\nBasketItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tproductId\x18\x02 \x01(\x05\x12\x13\n\x0bproductName\x18\x03 \x01(\t\x12\x11\n\tunitPrice\x18\x04 \x01(\x01\x12\x14\n\x0coldUnitPrice\x18\x05 \x01(\x01\x12\x10\n\x08quantity\x18\x06 \x01(\x05\x12\x12\n\npictureUrl\x18\x07 \x01(\t\"M\n\rOrderDraftDTO\x12\r\n\x05total\x18\x01 \x01(\x01\x12-\n\norderItems\x18\x02 \x03(\x0b\x32\x19.OrderingApi.OrderItemDTO\"~\n\x0cOrderItemDTO\x12\x11\n\tproductId\x18\x01 \x01(\x05\x12\x13\n\x0bproductName\x18\x02 \x01(\t\x12\x11\n\tunitPrice\x18\x03 \x01(\x01\x12\x10\n\x08\x64iscount\x18\x04 \x01(\x01\x12\r\n\x05units\x18\x05 \x01(\x05\x12\x12\n\npictureUrl\x18\x06 \x01(\t2t\n\x0cOrderingGrpc\x12\x64\n\x1e\x43reateOrderDraftFromBasketData\x12$.OrderingApi.CreateOrderDraftCommand\x1a\x1a.OrderingApi.OrderDraftDTO\"\x00\x42\x0f\xaa\x02\x0cGrpcOrderingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ordering_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\014GrpcOrdering'
  _globals['_CREATEORDERDRAFTCOMMAND']._serialized_start=31
  _globals['_CREATEORDERDRAFTCOMMAND']._serialized_end=113
  _globals['_BASKETITEM']._serialized_start=116
  _globals['_BASKETITEM']._serialized_end=259
  _globals['_ORDERDRAFTDTO']._serialized_start=261
  _globals['_ORDERDRAFTDTO']._serialized_end=338
  _globals['_ORDERITEMDTO']._serialized_start=340
  _globals['_ORDERITEMDTO']._serialized_end=466
  _globals['_ORDERINGGRPC']._serialized_start=468
  _globals['_ORDERINGGRPC']._serialized_end=584
# @@protoc_insertion_point(module_scope)
