# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\nCatalogApi\" \n\x12\x43\x61talogItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"G\n\x13\x43\x61talogItemsRequest\x12\x0b\n\x03ids\x18\x01 \x01(\t\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\x11\n\tpageIndex\x18\x03 \x01(\x05\"\xc8\x02\n\x13\x43\x61talogItemResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x19\n\x11picture_file_name\x18\x05 \x01(\t\x12\x13\n\x0bpicture_uri\x18\x06 \x01(\t\x12-\n\x0c\x63\x61talog_type\x18\x08 \x01(\x0b\x32\x17.CatalogApi.CatalogType\x12/\n\rcatalog_brand\x18\n \x01(\x0b\x32\x18.CatalogApi.CatalogBrand\x12\x17\n\x0f\x61vailable_stock\x18\x0b \x01(\x05\x12\x19\n\x11restock_threshold\x18\x0c \x01(\x05\x12\x1b\n\x13max_stock_threshold\x18\r \x01(\x05\x12\x12\n\non_reorder\x18\x0e \x01(\x08\"(\n\x0c\x43\x61talogBrand\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\'\n\x0b\x43\x61talogType\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\"{\n\x16PaginatedItemsResponse\x12\x11\n\tpageIndex\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\r\n\x05\x63ount\x18\x03 \x01(\x03\x12-\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x1f.CatalogApi.CatalogItemResponse2\xb3\x01\n\x07\x43\x61talog\x12P\n\x0bGetItemById\x12\x1e.CatalogApi.CatalogItemRequest\x1a\x1f.CatalogApi.CatalogItemResponse\"\x00\x12V\n\rGetItemsByIds\x12\x1f.CatalogApi.CatalogItemsRequest\x1a\".CatalogApi.PaginatedItemsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATALOGITEMREQUEST']._serialized_start=29
  _globals['_CATALOGITEMREQUEST']._serialized_end=61
  _globals['_CATALOGITEMSREQUEST']._serialized_start=63
  _globals['_CATALOGITEMSREQUEST']._serialized_end=134
  _globals['_CATALOGITEMRESPONSE']._serialized_start=137
  _globals['_CATALOGITEMRESPONSE']._serialized_end=465
  _globals['_CATALOGBRAND']._serialized_start=467
  _globals['_CATALOGBRAND']._serialized_end=507
  _globals['_CATALOGTYPE']._serialized_start=509
  _globals['_CATALOGTYPE']._serialized_end=548
  _globals['_PAGINATEDITEMSRESPONSE']._serialized_start=550
  _globals['_PAGINATEDITEMSRESPONSE']._serialized_end=673
  _globals['_CATALOG']._serialized_start=676
  _globals['_CATALOG']._serialized_end=855
# @@protoc_insertion_point(module_scope)
