# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from catalog_api.grpc_gen import catalog_pb2 as catalog__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItemById = channel.unary_unary(
                '/CatalogApi.Catalog/GetItemById',
                request_serializer=catalog__pb2.CatalogItemRequest.SerializeToString,
                response_deserializer=catalog__pb2.CatalogItemResponse.FromString,
                _registered_method=True)
        self.GetItemsByIds = channel.unary_unary(
                '/CatalogApi.Catalog/GetItemsByIds',
                request_serializer=catalog__pb2.CatalogItemsRequest.SerializeToString,
                response_deserializer=catalog__pb2.PaginatedItemsResponse.FromString,
                _registered_method=True)


class CatalogServicer:
    """Missing associated documentation comment in .proto file."""

    def GetItemById(self, request, context):
        """>>
        option (google.api.http) = {
        get: "/api/v1/catalog/items/{id}"
        };
        << 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemsByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItemById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemById,
                    request_deserializer=catalog__pb2.CatalogItemRequest.FromString,
                    response_serializer=catalog__pb2.CatalogItemResponse.SerializeToString,
            ),
            'GetItemsByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemsByIds,
                    request_deserializer=catalog__pb2.CatalogItemsRequest.FromString,
                    response_serializer=catalog__pb2.PaginatedItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CatalogApi.Catalog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CatalogApi.Catalog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Catalog:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetItemById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CatalogApi.Catalog/GetItemById',
            catalog__pb2.CatalogItemRequest.SerializeToString,
            catalog__pb2.CatalogItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItemsByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CatalogApi.Catalog/GetItemsByIds',
            catalog__pb2.CatalogItemsRequest.SerializeToString,
            catalog__pb2.PaginatedItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
